### ISSUE TITLE
建议，支持 thephpleague 的 Flysystem

### ISSUE THREAD

**Issue by wyzhcn** [upyun/php-sdk#10]
参见 [Flysystem](http://flysystem.thephpleague.com/)

Flysystem is a filesystem abstraction which allows you to easily swap out a local filesystem for a remote one. Technical debt is reduced as is the chance of vendor lock-in.

**Goals**
- Have a generic API for handling common tasks across multiple file storage engines.
- Have consistent output which you can rely on.
- Integrate well with other packages/frameworks.
- Be cacheable.
- Emulate directories in systems that support none, like AwsS3.
- Support third party plugins.
- Make it easy to test your filesystem interactions.
- Support streams for big file handling

**Comment by sabakugaara** [comment]
当前文件上传是支持大文件使用流式上传的，文件句柄作为参数传入即可

**Comment by tyua07** [comment]
@darkyoung  我完成了一个例子，[链接](https://github.com/tyua07/laravel-upload)！

**Comment by sabakugaara** [comment]
Good! @tyua07

**Comment by sabakugaara** [comment]
@darkyoung  新版的 sdk，会打包分块上传、音视频处理功能。也会考虑对`Flysystem`支持。
你有什么想法和建议吗？

**Comment by sabakugaara** [comment]
`3.0.0-RC1` 部分 API 设计参考了 Flysystem。提供了更多云处理的功能

**Comment by wyzhcn** [comment]
赞，之前看到忘了回复，有空来试用 😁

**Comment by sabakugaara** [comment]
欢迎提意见~ ^_^
