### ISSUE TITLE
请问如何通过composer调用class?

### ISSUE THREAD

**Issue by HuanMeng0** [upyun/php-sdk#12]
新增了composer支持，但是似乎无法调用？
看上去是没有namespace的问题

**Comment by sabakugaara** [comment]
当前的确不支持，sdk 还没有发布到 https://packagist.org/， 已经在准备更新中

**Comment by HuanMeng0** [comment]
THX

**Comment by sabakugaara** [comment]
已经支持 composer 安装，
```
composer require upyun/sdk
```
详细见 [使用说明](https://github.com/upyun/php-sdk#use%20instructions)

**Comment by HuanMeng0** [comment]
没有namespace 和 " Exception " 不改为 “\Exception” 真的没问题吗？

**Comment by sabakugaara** [comment]
没问题的，是在[全局空间](http://php.net/manual/zh/language.namespaces.global.php)下

**Comment by HuanMeng0** [comment]
THX!
