### ISSUE TITLE
Allow international customer?

### ISSUE THREAD

**Issue by geoff-nixon** [upyun/php-sdk#2]
Hi — I have a project that (one day might) need to have an agile CDN and/or compute core out of mainland China. I found your site via GitCafe.

But it seems I cannot sign up due to my phone number, as I tried:
+1 415 000 0000
+1 (415) 000-0000
00 1 415 000 0000
001 ...

It appears the offending regex is:

```
ng-pattern="/^(1(([358][0-9])|(47)|[8][01236789]))\d{8}$/"
```

Do you allow international customers?

[ I'm also not sure what "..QQ" is, Google can't translate it. ]

**Comment by sabakugaara** [comment]
@geoff-codes  Can I do anything for you now?  

tips: QQ is the most popular chat tool in China

**Comment by geoff-codes** [comment]
Oh my, I haven't thought about this in two years. Let me refresh my memory and get back to you! 😸

**Comment by sabakugaara** [comment]
anything you need, just contact me~ hubiao@upai.com
