### ISSUE TITLE
Class 'Upyun\Config' not found

### ISSUE THREAD

**Issue by xiaosaidanr** [upyun/php-sdk#32]
环境：laravel 5
安装方式：composer require upyun/sdk
错误：Class 'Upyun\Config' not found

**Comment by sabakugaara** [comment]
应该是因为 3.0 版本还没有正式放出，安装时需要指定版本号，今天会更新 3.0 正式版

**Comment by sabakugaara** [comment]
已经更新 3.0 正式版，可以指定版本号重新安装下

```
composer require upyun/sdk:3.0.0
```
