### ISSUE TITLE
此 SDK 如何获取某个文件的 Mimetype ？

### ISSUE THREAD

**Issue by JellyBool** [upyun/php-sdk#33]
看了源码和 issue ：https://github.com/upyun/php-sdk/issues/10

我实现完对 [Flysystem](http://flysystem.thephpleague.com/api/) 的支持，但是貌似还是没有看到在这个 SDK 中存在获取文件 `Mimetype` 的方法。

是我看漏了么？

**Comment by phy25** [comment]
你需要看 docs.upyun.com 的说明，看起来现在 REST API 是不支持返回 Mimetype 的。

在 2017年5月3日 下午11:38，Jelly Bool <notifications@github.com>写道：

**Comment by JellyBool** [comment]
@phy25 OK,那我自己实现返回 Mimetype 吧

**Comment by sabakugaara** [comment]
现在的确不支持，只实现了又拍云 API 支持的部分操作，可以增加支持 `getMimetype `

**Comment by JellyBool** [comment]
期待你更新下，我这边事太多... @sabakugaara

**Comment by sabakugaara** [comment]
OK

**Comment by sabakugaara** [comment]
done 可以安装最新版本 3.0.1

**Comment by sabakugaara** [comment]
有问题欢迎反馈~
