### ISSUE TITLE
异步拉取该怎么写？

### ISSUE THREAD

**Issue by BarryBravo** [upyun/php-sdk#35]
process方法在注释中写有异步拉取功能，但是不知道怎么用

**Comment by sabakugaara** [comment]
请问是指异步下载文件吗？

**Comment by sabakugaara** [comment]
暂时不支持异步拉取，我再更新下

**Comment by sabakugaara** [comment]
@BarryBravo 已经支持：https://github.com/upyun/php-sdk/pull/42
