### ISSUE TITLE
sdk 没有解决大文件上传的断点续传功能吗？

### ISSUE THREAD

**Issue by hoythan** [upyun/php-sdk#39]
sdk 没有解决大文件上传的断点续传功能吗？

**Comment by hoythan** [comment]
java sdk 巨丰富... php的我还得自己再写一套？

**Comment by hoythan** [comment]
我看源码里面是有这个功能的，但是判断后采用的。我再试试

**Comment by hoythan** [comment]
报错
```
cURL error 28: Operation timed out after 60000 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by sabakugaara** [comment]
支持断点续传 http://docs.upyun.com/api/rest_api/#Multi_upload，原分块上传从 sdk 移除了。
目前是根据文件大小自动选择的，方便用户使用。

看错误，应该是网络请求超时了，直接 `curl http://v0.api.upyun.com` 请求是成功的吗？

**Comment by sabakugaara** [comment]
有问题可以再打开 issue
