### ISSUE TITLE
[扩展]希望增加缓存刷新功能

### ISSUE THREAD

**Issue by kn007** [upyun/php-sdk#4]
非CDN空间。
每次去后台缓存刷新，很麻烦。
希望通过api方式来请求。谢谢！

**Comment by sabakugaara** [comment]
目前非cdn空间的缓存刷新api 并没有开放，不过如果文件出现覆盖，是会自动刷新缓存的。 不知道能否解决你的问题？

**Comment by kn007** [comment]
谢谢。使用文件覆盖的法子我试过了。以前还可以，现在不行，节点更新有时半小时后都没更新，我多次上传覆盖也一样，而去后台刷新，下一秒就可以了。囧。

**Comment by sabakugaara** [comment]
还有这情况， 经常出现的吗？

**Comment by kn007** [comment]
15年才出现的。。。以前都可以通过覆盖法。。。

**Comment by sabakugaara** [comment]
最近系统量级又上去了， 刷新任务是走队列的， 可能部分节点就慢了。 最近正在升级优化， 会尽快恢复到以前的刷新速度
