### ISSUE TITLE
上传图片和上传其他格式文件返回的响应头不同问题

### ISSUE THREAD

**Issue by feivorid** [upyun/php-sdk#48]
php7.1.7
laravel5.5
macos 系统最新版
chrome浏览器
laravel-admin 1.5.*
bootstrap file input 插件上传

我现在上传图片的时候一切正常  但是上传其他文件的时候得不到返回的路径  用debug 跟发现问题应该是出现这个方法中（也不一定是你们写的有问题） ：

![image](https://user-images.githubusercontent.com/5013223/40034161-3cfd9fec-582e-11e8-8fab-0d7d8badf5d7.png)

这个方法中`$headers`  上传图片文件和上传其他文件时候不一样
上传图片时候如图：
![image](https://user-images.githubusercontent.com/5013223/40034206-7157993c-582e-11e8-8a50-b6fda36bc45c.png)

上传其他文件时候headers内容如下图：
![image](https://user-images.githubusercontent.com/5013223/40034241-a6d9406a-582e-11e8-80fb-9052814191e6.png)

这样根据上面的代码  如果上传的不是图片 那么返回值为空数组  也导致了我出现上传非图片之后的东西时候获取不到 返回的路径的问题 ，  希望大大们 帮忙看看  🙏

**Comment by feivorid** [comment]
额   我看见你们代码的注释了   上传非图片的东西时候 故意返回空数组？   我日  这是为啥呢 ？  很难理解  ！！！！

**Comment by sabakugaara** [comment]
因为上传图片会有图片基本信息需要返回，例如宽高，这些信息会通过 `x-upyun` 前缀的 HTTP header 返回。非图片文件，没有这些信息。

**Comment by feivorid** [comment]
@sabakugaara   多谢您回答

我明白了    ，  是我用的第三方的laravel-upyun 的包write 的时候应该处理一下你们的sdk返回空数组  要不然 我这边整合的时候就有点问题    知道问题所在了  多谢解答
